# frozen_string_literal: true

# Generates the data in /src/data/name_markov_chain.rb,
# output is redirected there to create that file.
# Uses a file from https://github.com/smashew/NameDatabases as its source

require('open-uri')

NAMES_FILE = 'https://raw.githubusercontent.com/smashew/NameDatabases/master/NamesDatabases/first%20names/us.txt'

hash = URI.parse(NAMES_FILE).open.each_with_object({}) do |name, h|
  name = "__#{name.chomp}__"
  (name.length - 3).times do |i|
    combination = name[i, 2]
    next_letter = name[i + 2]
    h[combination] ||= {}
    h[combination][next_letter] ||= 0
    h[combination][next_letter] += 1
  end
end

puts("# frozen_string_literal: true\n")
puts('# This file was automatically generated by /misc/generate_name_markov_chain.rb')
puts("NAMES_MARKOV_CHAIN = #{hash.to_s.gsub(/\},/, "},\n")}")
