# Generates the data in /src/data/name_markov_chain.rb,
# output is redirected there to create that file.
# Uses a file from https://github.com/smashew/NameDatabases as its source

require "open-uri"

NamesFile = "https://raw.githubusercontent.com/smashew/NameDatabases/master/NamesDatabases/first%20names/us.txt"

hash = {}

URI.open(NamesFile).each_line do |name|
  name = "__#{name.strip}__"
  (name.length - 3).times do |i|
    combination = name[i, 2]
    hash[combination] = [] unless hash.include? combination
    hash[combination] << name[i + 2]
  end
end

puts "# This file was automatically generated by /misc/generate_name_markov_chain.rb"
puts "NamesMarkovChain = " + hash.to_s

